export const US_STATES = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New_York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming",
];

export const US_CITIES = {
    Alabama: ["Birmingham", "Montgomery", "Mobile", "Huntsville", "Tuscaloosa"],
    Alaska: ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan"],
    Arizona: ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale"],
    Arkansas: ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro"],
    California: ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Sacramento"],
    Colorado: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Boulder"],
    Connecticut: ["Bridgeport", "New Haven", "Stamford", "Hartford", "Waterbury"],
    Delaware: ["Wilmington", "Dover", "Newark", "Middletown"],
    "District of Columbia": ["Washington D.C."],
    Florida: ["Miami", "Orlando", "Tampa", "Jacksonville", "Tallahassee"],
    Georgia: ["Atlanta", "Augusta", "Savannah", "Columbus", "Macon"],
    Hawaii: ["Honolulu", "Hilo", "Kailua", "Kapolei"],
    Idaho: ["Boise", "Idaho Falls", "Pocatello", "Twin Falls"],
    Illinois: ["Chicago", "Springfield", "Naperville", "Peoria", "Rockford"],
    Indiana: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Bloomington"],
    Iowa: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City"],
    Kansas: ["Wichita", "Overland Park", "Kansas City", "Topeka"],
    Kentucky: ["Louisville", "Lexington", "Bowling Green", "Owensboro"],
    Louisiana: ["New Orleans", "Baton Rouge", "Lafayette", "Shreveport"],
    Maine: ["Portland", "Bangor", "Augusta", "Lewiston"],
    Maryland: ["Baltimore", "Annapolis", "Frederick", "Rockville"],
    Massachusetts: ["Boston", "Worcester", "Springfield", "Cambridge"],
    Michigan: ["Detroit", "Grand Rapids", "Ann Arbor", "Lansing"],
    Minnesota: ["Minneapolis", "Saint Paul", "Duluth", "Rochester"],
    Mississippi: ["Jackson", "Gulfport", "Biloxi", "Hattiesburg"],
    Missouri: ["Kansas City", "St. Louis", "Springfield", "Columbia"],
    Montana: ["Billings", "Missoula", "Great Falls", "Bozeman"],
    Nebraska: ["Omaha", "Lincoln", "Bellevue", "Grand Island"],
    Nevada: ["Las Vegas", "Reno", "Henderson", "Carson City"],
    "New Hampshire": ["Manchester", "Nashua", "Concord", "Portsmouth"],
    "New Jersey": ["Newark", "Jersey City", "Paterson", "Trenton", "Atlantic City"],
    "New Mexico": ["Albuquerque", "Santa Fe", "Las Cruces", "Roswell"],
    New_York: ["New York City", "Buffalo", "Rochester", "Albany", "Syracuse"],
    "North Carolina": ["Charlotte", "Raleigh", "Greensboro", "Durham", "Wilmington"],
    "North Dakota": ["Fargo", "Bismarck", "Grand Forks", "Minot"],
    Ohio: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron"],
    Oklahoma: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow"],
    Oregon: ["Portland", "Salem", "Eugene", "Bend", "Medford"],
    Pennsylvania: ["Philadelphia", "Pittsburgh", "Harrisburg", "Allentown"],
    "Rhode Island": ["Providence", "Warwick", "Cranston", "Newport"],
    "South Carolina": ["Columbia", "Charleston", "Greenville", "Myrtle Beach"],
    "South Dakota": ["Sioux Falls", "Rapid City", "Pierre"],
    Tennessee: ["Nashville", "Memphis", "Knoxville", "Chattanooga"],
    Texas: ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth"],
    Utah: ["Salt Lake City", "Provo", "Ogden", "St. George"],
    Vermont: ["Burlington", "Montpelier", "Rutland"],
    Virginia: ["Richmond", "Virginia Beach", "Norfolk", "Alexandria"],
    Washington: ["Seattle", "Spokane", "Tacoma", "Olympia"],
    "West Virginia": ["Charleston", "Huntington", "Morgantown"],
    Wisconsin: ["Milwaukee", "Madison", "Green Bay", "Kenosha"],
    Wyoming: ["Cheyenne", "Casper", "Laramie", "Gillette"],
};
